{"name": "Создание заказа с цветом: []", "status": "passed", "description": "Проверка создания заказа с различными вариантами цветов", "steps": [{"name": "Создать заказ", "status": "passed", "parameters": [{"name": "payload", "value": "{'firstName': 'miydnaxb', 'lastName': 'zzayaolx', 'address': 'ulylqycwzv, 59 apt.', 'metroStation': '109', 'phone': '+72070835115', 'rentTime': 4, 'deliveryDate': '2024-12-31', 'comment': 'uukfsfngyjllsgj'}"}], "start": 1761487127870, "stop": 1761487128592}, {"name": "Отмена заказа track: 793218", "status": "passed", "steps": [{"name": "Отменить заказ с трек-номером: 793218", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='qa-scooter.praktikum-services.ru', port=443): Max retries exceeded with url: /api/v1/orders/cancel (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000254AB2179D0>, 'Connection to qa-scooter.praktikum-services.ru timed out. (connect timeout=None)'))\n", "trace": "  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\there\\Sprint_7\\api\\orders_api.py\", line 53, in cancel_order\n    return requests.put(ORDERS_CANCEL, json={\"track\": track_number})\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 130, in put\n    return request(\"put\", url, data=data, **kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\there\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 507, in send\n    raise ConnectTimeout(e, request=request)\n"}, "parameters": [{"name": "track_number", "value": "793218"}], "start": 1761487128592, "stop": 1761487149617}], "start": 1761487128592, "stop": 1761487149619}], "parameters": [{"name": "color", "value": "[]"}], "start": 1761487127870, "stop": 1761487149619, "uuid": "b91adc0b-d31c-42b9-8cf9-946cb56a9a99", "historyId": "ee7828b70e23c01467b35937899b2ce3", "testCaseId": "9206a813de1fc59c8854ddec19a83b57", "fullName": "tests.test_order_create.TestOrderCreate#test_create_order_with_colors", "labels": [{"name": "suite", "value": "Создание заказа"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestOrderCreate"}, {"name": "host", "value": "Astti-Legion"}, {"name": "thread", "value": "132044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_create"}]}