{"name": "Нельзя создать двух одинаковых курьеров", "status": "failed", "statusDetails": {"message": "AssertionError: Неверное сообщение об ошибке: {'code': 409, 'message': 'Этот логин уже используется. Попробуйте другой.'}\nassert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "tests/test_courier_create.py:52: in test_create_duplicate_courier_fails\n    assert response_data.get(\"message\") == \"Этот логин уже используется\", \\\nE   AssertionError: Неверное сообщение об ошибке: {'code': 409, 'message': 'Этот логин уже используется. Попробуйте другой.'}\nE   assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE     \nE     - Этот логин уже используется\nE     + Этот логин уже используется. Попробуйте другой."}, "description": "Проверка, что при попытке создать курьера с существующим логином возвращается ошибка 409", "steps": [{"name": "Создать курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'cqjbsyhagf', 'password': 'qmrfmcczav', 'firstName': 'zvrdbwvkch'}"}], "start": 1761077300097, "stop": 1761077300743}], "start": 1761077300097, "stop": 1761077300747, "uuid": "2a08cb2b-2377-447f-bffb-2bd968066450", "historyId": "c6feda5d57d30d251035cdbf2da16a0f", "testCaseId": "c6feda5d57d30d251035cdbf2da16a0f", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_duplicate_courier_fails", "labels": [{"name": "suite", "value": "Создание курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "MacBook-Air-Konstantin.local"}, {"name": "thread", "value": "15999-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}